# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-logging.config
  namespace: {{ .Release.Namespace }}	
data:
  config.yaml: |
    apiVersion: logging.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
{{- if .Values.config.shootPurposesWithNodeLogging }}
    shootPurposesWithNodeLogging:
{{ toYaml .Values.config.shootPurposesWithNodeLogging | indent 6 }}
{{- end }}
{{- if .Values.config.featureGates }}
    featureGates:
{{ toYaml .Values.config.featureGates | indent 6 }}
{{- end }}