{{- if .Values.rbacSidecarEnabled }}
apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress from Prometheus to loki pods and ports named 'telegraf' in the PodSpecification.
  name: allow-from-prometheus-to-loki-telegraf
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
{{ toYaml .Values.labels | indent 8 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
          gardener.cloud/role: monitoring
          role: monitoring
    ports:
    - port: telegraf
      protocol: TCP
  policyTypes:
  - Ingress
  egress: []
{{- end}}
