{{- if .Values.rbacSidecarEnabled }}
apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
{{- if semverCompare "< 1.22-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header X-Scope-OrgID operator;"
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
{{- if semverCompare ">= 1.22-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.class }}
{{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
        path: {{ .backendPath }}
        pathType: Prefix
  {{- end }}
{{- end }}
