apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
{{ toYaml .Values.labels | indent 4 }}
immutable: true
data:
{{ include "loki.config.data" . | indent 2 }}
