apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: metrics
    targetPort: metrics
{{- if .Values.rbacSidecarEnabled }}
  - port: {{ .Values.kubeRBACProxy.port }}
    protocol: TCP
    name: external
    targetPort: {{ .Values.kubeRBACProxy.port }}
  - port: {{ .Values.telegraf.port }}
    protocol: TCP
    name: telegraf
    targetPort: {{ .Values.telegraf.port }}
{{- end }}
  selector:
{{ toYaml .Values.labels | indent 4 }}
