{{- if .Values.rbacSidecarEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
{{ toYaml .Values.labels | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
immutable: true
data:
{{ include "telegraf.config.data" . | indent 2 }}
{{- end }}
