# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/logging
  tag: latest
  pullPolicy: IfNotPresent

serviceName: logging
replicaCount: 1

resources: {}

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

ignoreResources: false

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 30m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

gardener:
  version: ""

## settings for metrics, e.g. scraping by seed-prometheus
#
metrics:
  ## enable metrics scraping
  ##
  port: 8080
  enableScraping: true

#  staticFilterList:
#    - network: 1.2.3.4/31
#      policy: BLOCK_ACCESS
#    - network: 5.6.7.8/32
#      policy: BLOCK_ACCESS
#    - network: ::2/128
#      policy: BLOCK_ACCESS
#
#  downloaderConfig:
#    endpoint: https://filterlist.example.com/some/path
#    oauth2Endpoint: https://auth.example.com/oauth2/token
#    refreshPeriod: 1h
#
#  oauth2Secret:
#    clientID: 1-2-3-4
#    clientSecret: secret!!
#    client.crt.pem: |
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    client.key.pem: |
#      -----BEGIN PRIVATE KEY-----
#      ...
#      -----END PRIVATE KEY-----