# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/logging
  tag: latest
  pullPolicy: IfNotPresent

serviceName: logging
replicaCount: 1

resources: {}

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

ignoreResources: false

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 30m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"

gardener:
  version: ""

## settings for metrics, e.g. scraping by seed-prometheus
#
metrics:
  ## enable metrics scraping
  ##
  port: 8080
  enableScraping: true

healthPort: 8081

config:
  shootPurposesWithNodeLogging:
    - "evaluation"
    - "development"
  featureGates:
    shootNodeLoggingEnabled: false
    eventLoggingEnabled: true

webhookConfig:
  servicePort: 443
  serverPort: 10251